---
# Example test file
type: testrun
label: test-iperf
spec:
    targettype: group
    source:
        name: agent-dc
        app: iperf
        args: "-c {{ target }}"
    target:
        name: agent-hq
        app: iperf
        args: "-s"
