---
# Example test file
type: testrun
label: test-ping-dns-dc
spec:
  targettype: uncontrolled
  target:
    name: agent-dc
    app: ping
    args: "-c 10"
  source:
    name: agent-dc

  target:
  - 4.2.2.2
  - 8.8.8.8
